feature9/added pre-commit configuration and dependencies
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #12
Opened 2023-09-09 10:40 UTC by Alex386386

Проверь пожалуйста наполнение файла .pre-commit-config.yaml и правильно ли создана зависимость в файле pyproject.toml, чтобы эта зависимость не вызвала проблем у других людей. Локально pre-commit отрабатывает без проблем и исправляет файлы.

2023-09-10 21:07 UTC, Yana-Denisova requested changes
Давай еще будем добавлять в комментарии к ПР краткое описание и ссылку на задачу в ноушн. Спасибо :)

2023-09-10 21:07 UTC, Yana-Denisova commented on pyproject.toml
> +[tool.poetry.group.dev.dependencies]
Если при выполнении команд poetry install и poetry update поставить флаг --no-dev: dev пакеты не будут устанавливаться или обновляться , так же можно удалить только dev пакеты poetry remove с флагом --dev . В целом без флагов они должны автоматически установиться у всех ребят, но можно и воспользоваться опцией для конкретной дев группы. Можно оставить как есть, должно работать.

2023-09-11 08:04 UTC, Alex386386 reviewed
resolved

2023-09-13 09:39 UTC, Yana-Denisova approved these changes

2023-09-13 12:45 UTC, merged