Добавил команду stop
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #13
Opened 2023-09-11 21:32 UTC by v-mcsimoff

Создал файл для обработки команд бота bot\conversations\command_application.py, реализовал функцию async def stop, добавил её в application.py. [Задача в Notion](https://www.notion.so/4a6a147b8cdc4f9fb7e3b40e32b2c444?v=0f1cc0f61dcf40b6a287308b402c1a65&p=2e9661f97af5485ba07056bf126c8ba7&pm=s)

2023-09-13 09:56 UTC, Yana-Denisova requested changes
Давай в названии к Пр добавим префикс с типом и номером задачи

2023-09-13 09:56 UTC, Yana-Denisova commented on src/bot/conversations/command_application.py
> +async def stop(update: Update, context):
context: ContextTypes.DEFAULT_TYPE

2023-09-13 09:56 UTC, Yana-Denisova commented on src/bot/conversations/command_application.py
> +STOP_MESSAGE = "Бот остановлен."
Давай подтянем текст из констант когда Мария смерджит свой Пр

2023-09-13 15:53 UTC, v-mcsimoff commented on src/bot/conversations/command_application.py
> +async def stop(update: Update, context):
Название изменил, ContextTypes добавил.

2023-09-13 15:57 UTC, v-mcsimoff commented on src/bot/conversations/command_application.py
> +STOP_MESSAGE = "Бот остановлен."
STOP_MESSAGE импортировал

2023-09-14 13:32 UTC, Yana-Denisova approved these changes

2023-09-14 15:04 UTC, merged