Feature13/access check
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #15
Opened 2023-09-15 10:31 UTC by Alex386386

Добавил функционал проверки кода доступа и последующий вывод стикера с сообщением или же повторная проверка.
Ссылка на задачу в Notion: https://www.notion.so/feature-13-9eb32a797c2c4a28bb656735427b51d3?pvs=4

2023-09-16 11:04 UTC, Yana-Denisova requested changes

2023-09-16 11:04 UTC, Yana-Denisova commented on src/bot/handlers.py
> +async def greeting_callback(
давай данные функции перенесем из хендлерс в src/bot/conversations/main_application.py

2023-09-17 11:27 UTC, Alex386386 commented on src/application.py
> +    conv_handler = ConversationHandler(
resolved

2023-09-17 11:27 UTC, Alex386386 commented on src/bot/utils.py
> +STICKER_ID: str = (
resolved

2023-09-18 11:55 UTC, Yana-Denisova requested changes

2023-09-18 11:55 UTC, Yana-Denisova commented on src/bot/constants/text.py
> +    "Верно! Выбери интересующую тебя тему из списка"
Там слово слипается 
```suggestion
    "Верно! Выбери интересующую тебя тему из списка "
```

2023-09-18 11:55 UTC, Yana-Denisova commented on src/bot/conversations/main_application.py
> +    update: Update,
Давай обновим по этому файлу все докстринги для функций, напишем на русском языке. Начало с большой буквы и не забудем точку в конце, Перед кавычками не надо пробелов если докстринг в одну строчку, если текста много кавычки переносим на другую строчку .

2023-09-18 17:00 UTC, Yana-Denisova approved these changes

2023-09-18 17:21 UTC, merged