feuture15: add menu_contact_list
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #18
Opened 2023-09-17 09:21 UTC by Maria50538810

feature 15: кнопка “Список контактов”. Добавлена обработка нажатия на клавиатуре Меню Список контактов.

https://www.notion.so/feature-15-3e825f7f91564a1195a966aa51a8681d?pvs=4

2023-09-18 14:14 UTC, Yana-Denisova requested changes

2023-09-18 14:14 UTC, Yana-Denisova commented on src/application.py
> +    app.add_handler(CallbackQueryHandler(menu_button))
ориентируйся на 13 фичу https://github.com/Studio-Yandex-Practicum/vtoroe_dyhanie/tree/feature13/access_check

2023-09-19 18:15 UTC, Yana-Denisova requested changes

2023-09-19 18:15 UTC, Yana-Denisova commented on src/application.py
> +    app.add_handler(CallbackQueryHandler(menu_button))
подтяни код из девелоп там появился конверсейшн хендлер, сделаем через него

2023-09-27 07:50 UTC, Yana-Denisova requested changes

2023-09-27 07:50 UTC, Yana-Denisova commented on src/bot/constants/button.py
> +NUMBER_OF_COLUMNS = 2
пока не решено

2023-09-27 07:50 UTC, Yana-Denisova commented on src/bot/conversations/contact_list_application.py
> +    """Отправляет сообщения с приглашением
не забудем точку в конце предложения

2023-09-27 07:50 UTC, Yana-Denisova commented on src/bot/conversations/main_application.py
> +    return ConversationHandler.END
нет новой строки в конце файла

2023-09-27 07:50 UTC, Yana-Denisova commented on src/bot/utils.py
> +def build_menu(buttons: list, n_cols: int,
где это используется?

2023-09-27 18:32 UTC, Maria50538810 commented on src/bot/utils.py
> +def build_menu(buttons: list, n_cols: int,
Уже нигде не используется ) 
Почистила.

2023-09-28 16:50 UTC, Yana-Denisova requested changes
Подтяни актуальный код из девелоп(там есть изменения которые повлияют на твой код) и встрой туда свою фичу, протестируй локально

2023-09-28 16:50 UTC, Yana-Denisova commented on src/bot/constants/button.py
> +NUMBER_OF_COLUMNS = 2
все еще нет новой строки в конце файла

2023-09-29 11:35 UTC, Yana-Denisova approved these changes
после мерджа обязательно протестируй код из девелоп и убедись что все корректно смерджилось и работает, если появится ошибка то сразу пиши, сделаем фикс

2023-09-30 09:52 UTC, merged