feature18/add button "Knowledge base"
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #20
Opened 2023-09-18 17:02 UTC by AndreyKilanov

Создал кнопу и сообщение "База знаний".
[Ссылука на таску](https://www.notion.so/4a6a147b8cdc4f9fb7e3b40e32b2c444?v=0f1cc0f61dcf40b6a287308b402c1a65&p=faf961ef32a54d27892f79461f52cf6d&pm=s)

2023-09-19 18:14 UTC, Yana-Denisova requested changes

2023-09-19 18:14 UTC, Yana-Denisova commented on src/bot/handlers.py
> +
подтяни код из девелоп там появился конверсейшн хендлер, сделаем через него

2023-09-19 18:14 UTC, Yana-Denisova commented on src/bot/conversations/menu_application.py
> +    """Send message with knowledge base"""
давай напишем все докстринги на русском и в конце не забудем точку

2023-09-19 18:14 UTC, Yana-Denisova commented on src/application.py
> +    app.add_handler(knowledge_base_handler)
подтяни код из девелоп там появился конверсейшн хендлер, сделаем через него

2023-09-20 19:46 UTC, AndyFebruary74 commented
Подтянул изменения, добавил в ConversationHandler менюшку и вставил туда месседж. Исправил докстрингу

2023-09-25 18:29 UTC, Yana-Denisova requested changes

2023-09-25 18:29 UTC, Yana-Denisova commented on src/bot/handlers.py
> +        MENU: [
решили делать как в 23 пр

2023-09-28 16:47 UTC, Yana-Denisova requested changes
Подтяни актуальный код из девелоп и встрой туда свою фичу, протестируй локально

2023-09-29 13:22 UTC, AndreyKilanov commented
Переделал таску. Добавил переход по кнопке в main_application. Сделал вывод сообщения и активную кнопку Назад. Добавил Стейт и Колбэк.

2023-09-29 14:49 UTC, Yana-Denisova approved these changes
после мерджа обязательно убедись, что твоя фича работает и все корректно смерджилось

2023-09-30 12:52 UTC, merged