Feature 19 / FAQ section
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #22
Opened 2023-09-21 21:01 UTC by v-mcsimoff

Реализовал раздел FAQ в соответствии с согласованной с заказчиком схемой. [Задача в Notion](https://www.notion.so/4a6a147b8cdc4f9fb7e3b40e32b2c444?v=0f1cc0f61dcf40b6a287308b402c1a65&p=9e54f9068f054c9cb66fdda7f649cd19&pm=s)
Добавил дополнительный раздел меню, прописал необходимые тексты, добавил кнопку возврата в главное меню.

2023-09-25 18:28 UTC, Yana-Denisova requested changes

2023-09-25 20:37 UTC, v-mcsimoff commented on src/bot/conversations/menu_application.py
> +async def voluntarism_callback(
Перенёс в новый файл conversations/faq_application.py

2023-09-25 23:19 UTC, v-mcsimoff commented on src/bot/handlers.py
> +        MENU: [
Изменил

2023-09-27 07:40 UTC, Yana-Denisova requested changes

2023-09-27 07:40 UTC, Yana-Denisova commented on src/bot/conversations/faq_application.py
> +async def faq_callback(
давай добавим докстринг

2023-09-27 07:40 UTC, Yana-Denisova commented on src/bot/handlers.py
> +            MessageHandler(filters.Text(["FAQ"]), main_menu_actions_callback),
этот код точно работает? ты протестировал?

2023-09-27 08:47 UTC, v-mcsimoff commented on src/bot/handlers.py
> +            MessageHandler(filters.Text(["FAQ"]), main_menu_actions_callback),
Да, работает - нажатием кнопки FAQ вызывается раздел FAQ. Но ему нужно обрабатывать и другие команда тоже) Изменил на .TEXT

2023-09-27 08:48 UTC, v-mcsimoff commented on src/bot/conversations/faq_application.py
> +async def faq_callback(
Добавил

2023-09-27 17:36 UTC, v-mcsimoff commented
Добавил return status после каждой кнопки, так как без этого после возврата в главное меню повторно в FAQ не получалось зайти - он оставался в статусе FAQ

2023-09-28 16:49 UTC, Yana-Denisova requested changes
Подтяни актуальный код из девелоп ( там появились изменения) и встрой туда свою фичу, протестируй локально

2023-09-29 19:07 UTC, v-mcsimoff commented
> Подтяни актуальный код из девелоп ( там появились изменения) и встрой туда свою фичу, протестируй локально

Код подтянул, конфликты решил, протестировал локально, моя фича работает

2023-09-29 19:20 UTC, Yana-Denisova approved these changes
протестируй из девелоп после мерджа , надо убедиться что все корректно смерджилось

2023-09-29 20:10 UTC, merged