Feature17/feedback button
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #23
Opened 2023-09-23 16:38 UTC by MrProfessorCat

Добавлен обработчик кнопки "Обратная связь". В ответе выводится сообщение с ссылкой на страницу с формой обратной связи

2023-09-25 18:26 UTC, Yana-Denisova requested changes

2023-09-25 18:26 UTC, Yana-Denisova commented on src/bot/handlers.py
> +        MENU: [
решили делать как в 23 пр

2023-09-27 07:21 UTC, Yana-Denisova requested changes

2023-09-27 07:21 UTC, Yana-Denisova commented on src/bot/constants/state.py
> +FEEDBACK: int = 26
прям перестраховался))

2023-09-27 07:21 UTC, Yana-Denisova commented on src/bot/conversations/menu_application.py
> +    """Возвращает в главное меню"""
давай точку добавим в конце предложения

2023-09-27 08:12 UTC, MrProfessorCat commented on src/bot/constants/state.py
> +FEEDBACK: int = 26
Из main_menu (2), 6-я кнопка) = 26

2023-09-28 16:45 UTC, Yana-Denisova requested changes
Подтяни актуальный код из девелоп и встрой туда свою фичу, протестируй локально

2023-09-28 17:50 UTC, Yana-Denisova approved these changes

2023-09-28 18:18 UTC, merged