Feature23/basic information
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #24
Opened 2023-09-25 08:48 UTC by Alex386386

Полностью реализован раздел "основная информация" из главного меню. [Задача в Notion](https://www.notion.so/feature-23-d2fd0a2c3dfa41beb1f0958cda9ff250?pvs=4)
В остатках только текст для кнопок "график работы" и "список контактов". Весь остальной функционал выполнен согласно схеме.

2023-09-25 18:23 UTC, Yana-Denisova requested changes

2023-09-25 18:23 UTC, Yana-Denisova commented on src/bot/conversations/main_application.py
>      START_MESSAGE,
просто импортируем text а где нужно получаем значение через text.START_MESSAGE так мы избавимся от полотна импортов, мы все равно импортируем все тексты

2023-09-25 18:23 UTC, Yana-Denisova commented on src/bot/conversations/main_application.py
> +async def handle_organization_structure(query: CallbackQuery) -> None:
сделаем отдельный файл под этот блок

2023-09-25 18:23 UTC, Yana-Denisova commented on src/bot/keyboards.py
> +basic_information_keyboard = [
для раздела сделаем отдельный файл

2023-09-25 20:32 UTC, Maria50538810 commented on src/application.py
> +def main() -> None:  # noqa
Не знаю. Надо к Саше. Он пока не доступен.

2023-09-27 07:11 UTC, Yana-Denisova requested changes

2023-09-27 07:11 UTC, Yana-Denisova commented on src/bot/conversations/main_application.py
>  from bot.constants.text import (
просто импортируем text а где нужно получаем значение через text.START_MESSAGE так мы избавимся от полотна импортов, мы все равно импортируем все тексты

2023-09-27 07:11 UTC, Yana-Denisova commented on src/bot/conversations/main_application.py
>      START_MESSAGE,
это пока так и не решено

2023-09-27 07:11 UTC, Yana-Denisova commented on src/bot/conversations/basic_info_application.py
> +#    elif query_data == "schedule":
если этот пункт убрали из схемы и фичлиста, то надо удалить

2023-09-27 07:11 UTC, Yana-Denisova commented on src/bot/conversations/basic_info_application.py
> +    """Обработка клавиатуры отделов Фонда."""
Дикстринги это отлично, следующим ребятам, которые придут после вас будет проще и быстрее понять, что происходит в коде, улучшит читаемость кода. Давайте добавим ко всем функциям по всему файлу.

2023-09-27 07:11 UTC, Yana-Denisova commented on src/application.py
> +def main() -> None:  # noqa
Тогда вопрос все еще открыт

2023-09-27 07:11 UTC, Yana-Denisova commented on src/application.py
> +filterwarnings(  # noqa
так понимаю данная конструкция для того, чтобы в терминале при запуске убрать предупреждение? оно так сильно смущало?))

2023-09-27 18:26 UTC, Maria50538810 commented on src/application.py
> +filterwarnings(  # noqa
Это тоже вопрос к Саше.

2023-09-27 19:25 UTC, Alex386386 commented on src/application.py
> +def main() -> None:  # noqa
У меня интерпретатор выдавал предупреждение, мол неправильно оформленная аннотация. По этому поставил "# noqa", думаю если убрать проблем не будет. Поставил чисто чтобы предупреждение убрать.

2023-09-27 19:27 UTC, Alex386386 commented on src/application.py
> +filterwarnings(  # noqa
Да, меня смущало наличие предупреждения. А если оставить эту конструкцию без "# noqa" то в интерприетаторе вылазило предупреждение, и чтобы мне ничего глаза не мозолило, сделал подобным образом. Если надо убрать, то непроблема.

2023-09-27 19:41 UTC, Yana-Denisova requested changes
Перед отправкой ПР протестируйте локально и убедитесь, что все работает стабильно без ошибок, спасибо!

2023-09-27 19:41 UTC, Yana-Denisova commented on src/application.py
> +filterwarnings(  # noqa
ок давай пока оставим

2023-09-27 19:41 UTC, Yana-Denisova commented on src/bot/conversations/basic_info_application.py
> +from bot.constants.basic_info_text import(
13 строка получается лишняя

2023-09-27 19:41 UTC, Yana-Denisova commented on src/bot/conversations/basic_info_application.py
> +    await query.answer()
обратите внимание на эту конструкцию, добавьте где необходимо

2023-09-28 10:43 UTC, Yana-Denisova approved these changes
после мерджа с девелоп убедитесь что ваша фича и приложение работает стабильно, протестируйте

2023-09-28 15:52 UTC, merged