Fix6/about foundation
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #46
Opened 2023-10-16 19:51 UTC by Evgeniy-Golodnykh

Fix 6.
Поправил текст константы в файле about_fund_text.py согласно задаче https://www.notion.so/fix-6-cd6a5e5d974f4dc0a7b1e79140ff6de3?pvs=4
Смержил с текущей веткой develop, устранил конфликты.

2023-10-17 08:25 UTC, Yana-Denisova requested changes
В ПР точно попали все изменения которые нужны для текущей задачи?

2023-10-17 08:25 UTC, Yana-Denisova commented on src/bot/constants/about_fund_text.py
> +    "msg_1": "Для начала немного предыстории 👀",
решили, оставить везде одинарные кавычки

2023-10-17 08:36 UTC, Evgeniy-Golodnykh commented on src/bot/constants/about_fund_text.py
> +    "msg_1": "Для начала немного предыстории 👀",
Да, все изменения согласно заданию. Просто часть исправлений из задания Fix6 были в Fix7 и Ася Савельева их сделала раньше. Поэтому я оставил ее варианты (с одинарными кавычками). Остальной код был написан с двумя кавычками, поэтому я поправил только значения констант согласно Fix6, оформление не менял.

Если нужно менять всё на одинарные кавычки, то нужно полностью менять форматирование во всех файлах с константами.

2023-10-18 20:36 UTC, Yana-Denisova approved these changes

2023-10-18 20:38 UTC, merged