fix /help command
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #47
Opened 2023-10-16 21:45 UTC by Evgeniy-Golodnykh

Fix 9.
Добавил обработку команды /help согласно задаче https://www.notion.so/fix-9-help-abbd6e79043941d28dc0adad21980bcd?pvs=4
Смержил с текущей веткой develop, устранил конфликты.

2023-10-17 08:33 UTC, Yana-Denisova requested changes

2023-10-17 08:33 UTC, Yana-Denisova commented on src/bot/handlers/command_application.py
> +    app.add_handler(CommandHandler('help', help))
Ты точно протестировал работу данной фичи? Удали историю в боте и запусти снова из своей ветки и посмотри что получается :)

2023-10-17 08:40 UTC, Evgeniy-Golodnykh commented on src/bot/handlers/command_application.py
> +    app.add_handler(CommandHandler('help', help))
Да, само собой протестировал из своей ветки) при вводе команды /help выводится сообщение:
Если у тебя есть вопрос, присылай его на почту hr@vtoroe.ru

2023-10-18 20:27 UTC, Yana-Denisova requested changes
Давай добавим возможность ввода команды хелп через синее меню слева 
![image](https://github.com/Studio-Yandex-Practicum/vtoroe_dyhanie/assets/91561120/ef0effed-011a-4cd4-817a-af7f9464419a)

2023-10-18 20:38 UTC, Yana-Denisova commented
fix 9

2023-10-21 09:47 UTC, Evgeniy-Golodnykh commented
Добавил синее меню, подтянул актуальное состояние, исправил конфликты.

2023-10-21 11:29 UTC, Yana-Denisova requested changes

2023-10-21 11:29 UTC, Yana-Denisova commented on src/application.py
> +        .token(settings.telegram_token)
Запустила код из твоей ветки, меню появляется , но там нет нужных команд, попробуй сделать через  context.bot.set_my_commands()

2023-10-21 19:54 UTC, Yana-Denisova requested changes

2023-10-21 19:54 UTC, Yana-Denisova commented on src/bot/handlers/command_application.py
> +    return ConversationHandler.END
достаточно просто сообщения

2023-10-21 19:54 UTC, Yana-Denisova commented on src/bot/handlers/command_application.py
> +    return ConversationHandler.END
и тут тоже

2023-10-22 18:17 UTC, Yana-Denisova approved these changes

2023-10-22 18:34 UTC, merged