Added greeting handler
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #5
Opened 2023-09-07 21:44 UTC by MrProfessorCat

Added base handler to greet the user with /start command

2023-09-08 18:09 UTC, Yana-Denisova requested changes
в другом  [ПР](https://github.com/Studio-Yandex-Practicum/vtoroe_dyhanie/pull/6/files) мы создали менеджер настроек для бота, давай дождемся когда этот пр смерджат и ты подтянешь актуальный код из девелоп в свою ветку и прокинешь токен через эти настройки

2023-09-09 15:59 UTC, MrProfessorCat commented
> в другом [ПР](https://github.com/Studio-Yandex-Practicum/vtoroe_dyhanie/pull/6/files) мы создали менеджер настроек для бота, давай дождемся когда этот пр смерджат и ты подтянешь актуальный код из девелоп в свою ветку и прокинешь токен через эти настройки

2023-09-09 16:04 UTC, MrProfessorCat commented
Now telegram token is taking from env via pydantic settings

> в другом [ПР](https://github.com/Studio-Yandex-Practicum/vtoroe_dyhanie/pull/6/files) мы создали менеджер настроек для бота, давай дождемся когда этот пр смерджат и ты подтянешь актуальный код из девелоп в свою ветку и прокинешь токен через эти настройки

2023-09-10 20:44 UTC, Yana-Denisova approved these changes

2023-09-11 06:18 UTC, merged