refactoring4/Send_messages
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #50
Opened 2023-10-18 01:05 UTC by DNKer

Добавлен метод send_message, который отправляет сообщение и раскладку клавиатуры (файл about_fund_application.py). Используется в send_about_fund_message (отправляет сообщение и раскладку клавиатуры при нажатии кнопки "Миссия и основная цель"), send_things_path_message (отправляет сообщение и раскладку клавиатуры при нажатии кнопки "Путь вещей", send_fund_projects_message (отправляет сообщение и раскладку клавиатуры при нажатии кнопки "Проекты Фонда").

2023-10-20 11:04 UTC, Yana-Denisova requested changes

2023-10-20 11:04 UTC, Yana-Denisova commented on src/bot/handlers/about_fund_application.py
> +async def send_message(
Давай перенесем в utils.py и переиспользуем по другим файлам

2023-10-20 11:46 UTC, DNKer commented on src/bot/handlers/about_fund_application.py
> +async def send_message(
Да, была такая мысль. Хотел предложить.

2023-10-21 03:41 UTC, DNKer commented
Добавлено (включено) исправление [По задаче fix 11: привести docstring к общему виду](https://www.notion.so/4a6a147b8cdc4f9fb7e3b40e32b2c444?v=0f1cc0f61dcf40b6a287308b402c1a65&p=ad1fdcb765334085b464d1c4622d4151&pm=s)

2023-10-21 20:04 UTC, Yana-Denisova requested changes
Давай разделим на два пр отдельно задачу на отправку сообщений, отдельно докстринг и еще почему-то много изменений в текстах, вроде уже исправили все и задачи на это не было , надо чтобы в пр попали только файлы которые относятся к задаче, остальные не надо :)

2023-10-21 20:24 UTC, Yana-Denisova requested changes

2023-10-21 20:24 UTC, Yana-Denisova commented on src/bot/constants/about_fund_text.py
> +        r' ручки или пластиковые вешалки\)\. Производство осуществляется через'
Почему в коммит поопадает много изменений, которые не относятся к задаче ? :)

2023-10-22 09:53 UTC, DNKer commented on src/bot/constants/about_fund_text.py
> +        r' ручки или пластиковые вешалки\)\. Производство осуществляется через'
Приходится немного корректировать текст в части разметки markdown. Экранировать символы.

2023-10-22 11:39 UTC, DNKer commented
> Добавлено (включено) исправление [По задаче fix 11: привести docstring к общему виду](https://www.notion.so/4a6a147b8cdc4f9fb7e3b40e32b2c444?v=0f1cc0f61dcf40b6a287308b402c1a65&p=ad1fdcb765334085b464d1c4622d4151&pm=s)
Удалено из PR. Будет создана новая ветка и Pull Request

2023-10-22 18:30 UTC, Yana-Denisova requested changes

2023-10-22 18:30 UTC, Yana-Denisova commented on src/bot/constants/about_fund_text.py
> +        r' ручки или пластиковые вешалки\)\. Производство осуществляется через'
Просто не пуш в удаленный репозиторий лишние файлы да и все, принято в комммит добавлять один-два файла, с которыми работали и которые к задаче относятся , все папки и весь проект не нужно :) Или у тебя тут какая-то ошибка вылетает?

2023-10-23 01:09 UTC, DNKer commented on src/bot/constants/about_fund_text.py
> +        r' ручки или пластиковые вешалки\)\. Производство осуществляется через'
Да ошибка. Падает с просьбой экранировать спец символы. Здесь "." и ")"

2023-10-23 09:40 UTC, DNKer commented
Да ошибка. Падает с просьбой экранировать спец символы. Здесь "." и ")"

2023-10-24 13:46 UTC, Yana-Denisova approved these changes

2023-10-24 14:44 UTC, merged