feature 24: логирование
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #53
Opened 2023-10-20 07:00 UTC by Esperansa08

https://www.notion.so/feature-24-d45556809e0a4d5db8f4634dae4baea1?pvs=4
1. Настроена запись логов в отдельную папку data/logs (создается при отсутствии) и их вывод в стандартный поток вывода.
2. Установлено ограничение в 60 файлов и создание нового файла каждый день.
3. В менеджере настроек проекта определены параметры формата, пути и уровня логирования.
4. Каждое сообщение в журнале логов состоит из даты и времени события, названия регистратора, уровня важности события, описания события.

2023-10-20 09:48 UTC, Yana-Denisova requested changes

2023-10-20 09:48 UTC, Yana-Denisova commented on src/bot/core/logger.py
> +logging.basicConfig(
посмотри в сторону logging.config.dictConfig() https://docs-python.ru/standart-library/paket-logging-python/funktsija-dictconfig-modulja-logging-config/

2023-10-20 15:55 UTC, DNKer commented on src/bot/core/logger.py
> +logging.basicConfig(
Мне кажется в проекте еще не хватает такой (или подобной) конструкции, суть которой обработка завершения работы (неаварийной, по команде "оператора"):
```python
if __name__ == '__main__':
    try:
        main()
    except KeyboardInterrupt:
        logging.info('Бот "{__name__}" завершил свою работу по <<Ctr+C>>.')
    finally:
        sys.exit()
   ```
   Так для дискуссии и (пища для) размышления ;-)

2023-10-21 17:13 UTC, Esperansa08 commented on src/bot/core/logger.py
> +logging.basicConfig(
Внесла изменения по ревью:  logging.basicConfig заменен на logging.config.dictConfig.

2023-10-21 19:44 UTC, Yana-Denisova requested changes

2023-10-21 19:44 UTC, Yana-Denisova commented on src/bot/core/settings.py
> +    logging_level: int = logging.DEBUG
logging_level: str = 'INFO'

2023-10-21 19:44 UTC, Yana-Denisova commented on src/bot/core/logger.py
> +from logging.config import dictConfig
на третьей строке уже импортировали logging.config, в таком случае просто  на 45 строке можно вот так logging.config.dictConfig(LOGGING)

2023-10-21 19:44 UTC, Yana-Denisova commented on src/bot/core/settings.py
> +from bot.core.logger import logger      # noqa
это точно тут нужно?

2023-10-22 07:08 UTC, Yana-Denisova approved these changes

2023-10-22 07:12 UTC, merged