feature 26: отправка писем на электронную почту
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #56
Opened 2023-10-22 07:13 UTC by Esperansa08

https://www.notion.so/feature-26-bca9d41f76ad4ed7b75036f4296815b6?pvs=4
1. Настроила и протестировала отправление сообщений
2. Введены тестовые значения заголовка и текста письма
3. В функции запрашивается пароль для smtp сервера.

2023-10-22 18:27 UTC, Yana-Denisova requested changes

2023-10-22 18:27 UTC, Yana-Denisova commented on src/bot/utils.py
> +    Send an email
Молодец! давай сделаем докстринг на русском как по всему проекту

2023-10-22 18:27 UTC, Yana-Denisova commented on src/bot/utils.py
> +    smtp_server = "smtp.gmail.com"
давай вынесем в менеджер проекта ( сеттнгз ) вот эти настройки, пароль тоже будем потом добавлять через енв

2023-10-22 18:27 UTC, Yana-Denisova commented on src/bot/utils.py
> +    smtp_server = "smtp.gmail.com"
Сможешь попробовать через яндекс сделать? есть риск что gmail в перспективе не смогут использовать, лучше перестраховаться

2023-10-23 12:55 UTC, Esperansa08 commented on src/bot/utils.py
> +    smtp_server = "smtp.gmail.com"
Настроила.

2023-10-24 08:17 UTC, Yana-Denisova requested changes

2023-10-24 08:17 UTC, Yana-Denisova commented on .env.example
> +PASSWORD_EMAIL='ygjxrtrwtl'    # Пароль приложения для почты
отличная идея сразу добавить пример , добавь еще пустую строку в конце файла

2023-10-24 13:57 UTC, Yana-Denisova requested changes

2023-10-24 13:57 UTC, Yana-Denisova commented on src/bot/utils.py
> +subject = 'Тестирование'
Молодец! Проверила на своих почтах, все работает, пока оставим в таком виде, потом уберем тестовые тексты, когда уже данная функция будет включена в работу бота, пока давай закомментируем данные для тестирования и вызов, но оставим их в ПР, чтобы следующей когорте было проще разобраться. Спасибо!

2023-10-25 18:14 UTC, Yana-Denisova approved these changes

2023-10-26 03:07 UTC, merged