feature 29: отправка сообщений по email
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #69
Opened 2023-11-06 10:39 UTC by evgeny-dmitrievich

Попытался реализовать отправку сообщений на email поддержки по задача:
https://www.notion.so/feature-29-email-b89cec85078941a48679fb9ab730f360?pvs=4

2023-11-10 17:20 UTC, Yana-Denisova requested changes

2023-11-10 17:20 UTC, Yana-Denisova commented on README.md
> +Создайте в корневой папке проекта файл .env и заполни данные по шаблону:
Хорошая идея добавить шаблон в ридми, давай еще добавим в .env.example

2023-11-10 17:20 UTC, Yana-Denisova commented on src/bot/handlers/command_application.py
> +GET_USER_QUESTION = 1
давай вынесем стейт в src\bot\constants\state.py

2023-11-10 17:20 UTC, Yana-Denisova commented on src/bot/handlers/command_application.py
> +async def get_user_question_callback(
Тестировал, что будет, если начать вводить другие команды или нажимать на кнопки меню после вызова хелп на стадии ввода вопроса пользователя?

2023-11-10 17:20 UTC, Yana-Denisova commented on src/bot/handlers/command_application.py
> +    subject = 'Вопрос от пользователя'
Может укажем в сообщении, что вопрос от пользователя в телеграмм? Или как-то пропишем что это юзернейм или ник, а то вдруг они не поймут что это телеграмовский ник? Что думаешь? Им же может много писем приходить , тема письма должна быть "Обращение в поддержку телеграмм бота", чтобы было понятно сразу по теме письма , что там внутри.

2023-11-13 07:58 UTC, evgeny-dmitrievich commented on src/bot/core/settings.py
> +    smtp_server: str
Там это уже есть)

2023-11-13 07:58 UTC, evgeny-dmitrievich commented on README.md
> +Создайте в корневой папке проекта файл .env и заполни данные по шаблону:
Там это уже есть)

2023-11-13 07:58 UTC, evgeny-dmitrievich commented on src/bot/handlers/command_application.py
> +GET_USER_QUESTION = 1
Готово)

2023-11-13 08:01 UTC, evgeny-dmitrievich commented on src/bot/handlers/command_application.py
> +async def get_user_question_callback(
Протестировал и понял, что недоработал, исправил и теперь по кнопкам команды отрабатываются, пришлось перейти функцию начала разговора из main в command, потому что была кольцевая зависимость при импорте модулей.

2023-11-13 08:07 UTC, evgeny-dmitrievich commented on src/bot/handlers/command_application.py
> +    subject = 'Вопрос от пользователя'
Да, думаю тогда сделаем тему письма: Обращение в поддержку телеграм бота
Никнейм в телеграм: 
Вопрос:
Коротко и понятно)

2023-11-13 11:28 UTC, Yana-Denisova requested changes

2023-11-13 11:28 UTC, Yana-Denisova commented on README.md
> +Создайте в корневой папке проекта файл .env и заполни данные по шаблону:
Этот файл не попал в пуллреквест

2023-11-13 11:28 UTC, Yana-Denisova commented on src/bot/utils.py
> +class QuestionModel(BaseModel):
Давай для моделей пайдентик сделаем отдельный файл schemas.py

2023-11-13 11:37 UTC, evgeny-dmitrievich commented on README.md
> +Создайте в корневой папке проекта файл .env и заполни данные по шаблону:
Эти данные уже были в том файле, который склонировался вместе с проектом.

2023-11-13 11:38 UTC, evgeny-dmitrievich commented on README.md
> +Создайте в корневой папке проекта файл .env и заполни данные по шаблону:
Или я наверное не до конца понимаю что добавить)

2023-11-13 11:40 UTC, evgeny-dmitrievich commented on src/bot/utils.py
> +class QuestionModel(BaseModel):
Готово

2023-11-13 14:30 UTC, Yana-Denisova approved these changes
Молодец, можешь мерджить

2023-11-13 15:23 UTC, merged