11.11
Studio-Yandex-Practicum/vtoroe_dyhanie pull request #72
Opened 2023-11-11 08:52 UTC by AleksNovo

Полностью реализована логика отложенных сообщений по ветке "Новичек" и "Руководитель"
Ссылка на задачу в notion:

2023-11-13 18:18 UTC, AleksNovo commented
Полностью реализована логика отложенных сообщений по ветке "Новичек" и "Руководитель"
Переименовал ПР. Модели pydantic теперь в файле schemas.py
Ссылка на задачу в notion:
https://www.notion.so/feature-30-5ff0cae13e2a474ab032136c70b85908?pvs=4

2023-11-13 19:11 UTC, Yana-Denisova requested changes
Название ПР пока не изменилось

2023-11-13 19:11 UTC, Yana-Denisova commented on src/bot/handlers/schemas.py
> +from pydantic import BaseModel, validator
такой файл уже в константс твой коллега создал

2023-11-13 19:14 UTC, Yana-Denisova requested changes

2023-11-13 19:14 UTC, Yana-Denisova commented on src/bot/handlers/onboarding_application.py
> +            bot, 25*86400, update.message.chat_id,
Тут уже из фичлиста время?

2023-11-13 20:10 UTC, AleksNovo commented on src/bot/handlers/onboarding_application.py
> +            bot, 25*86400, update.message.chat_id,
Да. 25, 40 и 85 дней

2023-11-13 20:32 UTC, AleksNovo commented on src/bot/handlers/schemas.py
> +from pydantic import BaseModel, validator
Понял. Перенес модель в файл к коллеге

2023-11-14 11:58 UTC, Yana-Denisova requested changes

2023-11-14 11:58 UTC, Yana-Denisova commented on src/bot/handlers/onboarding_application.py
> +    try:
вижу, эта проверка есть в нескольких местах, можно вынести ее в утилс и переиспользовать

2023-11-14 15:52 UTC, AleksNovo commented
Внес изменения согласно ревью

2023-11-16 17:08 UTC, Yana-Denisova approved these changes
Прогони линтерами перед мерджем , а то воркфлоу не отработает и на сервере бот упадет с ошибкой

2023-11-16 18:47 UTC, AleksNovo commented
Прогнал все файлы (в которых я делал изменения) через flake8. Все "шероховатости" устранены.

2023-11-16 18:49 UTC, Yana-Denisova commented
можешь мерджить

2023-11-16 19:02 UTC, merged